### ISSUE TITLE
Create a translation

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#10]
As an editorial user, I want to create a translation of a book by clicking a button, so that it's easy to translate a book alongside its master version.

**Comment by arthurattwell** [comment]
Me, 10 Oct 2016:

> Translations need lots of thought. Best practice may be to create translations in subfolders of the book named for their language codes, because this keeps translations literally close to their master versions (as opposed to treating them like adaptations in forks). But this might not work with our metadata include that uses the path to read the correct metadata from `_meta.yml`.

**Comment by arthurattwell** [comment]
I've made progress on a model for translations, currently testing it in a [standalone repo here](https://github.com/arthurattwell/eb-translations). 

This model starts with the notion that translations and adaptations are very different:

* In an adaptation, anything can change: text, images, structure. For that reason, adaptations should be forks (for light adaptations that might contribute changes back to the original) or clones (no assumed connection to the upstream version).
* In a translation, only the language of the text changes. Translations share elements like images (except where the images themselves include text) and design.

So technically, translations are simply subfolders of `book/text`. Each subfolder is named for its language code, e.g. `book/text/fr`. There is no technical connection between the files in that subfolder and those in the parent. We expect that for most translations the files will have the same names and structure, but it's not required.

Subfolders might also contain other elements, like draft chapters or ancillary materials (e.g. worksheets).

We identify a given subfolder of `book/text` in `meta.yml`. In the metadata for a work, we list `translations`. E.g.:

``` yaml
works:
  - directory: "book"
    title: "The Title"
      ...
    products: # Metadata for each product for this title (only use values that override parent metadata)
      ...
    translations:
      -
        directory: xh
        language: xh
        title: Title in Xhosa
        products:
          ...
      -
        directory: fr
        language: fr
        title: Title in French
        products:
          ...
```

Each node in `translations` is then a full metadata listing, as for `work`. A translation inherits its parent/source work's metadata except where it's been overridden here. This lets us specify different file lists, publication dates, authors, and so on, for any given translation.

Using subfolders means we can't use relative paths like `../images` in parent versions and paste them into subfolders. So we now have a variable, `{{ path-to-book-directory }}`, to use instead. (We need relative paths for epub especially.) This makes it really easy to paste, say, the English files into a translation subfolder as-is and have it work.

The output scripts can then support choosing a subfolder for output.
